### ISSUE TITLE
Is there any way to remove padding from Horizontal Progress bar?

### ISSUE THREAD

**Issue by Pika1998** [react-native-progress-view/progress-bar-android#47]
# Question

**Comment by Naturalclar** [comment]
@Pika1998 The padding in horizontal progress bar seems to be a limitation of the ProgressBar module that used in this package.
https://stackoverflow.com/questions/14171471/remove-vertical-padding-from-horizontal-progressbar

Possible workaround would be to add negative margins to the progress bar, which worked for me.
```
<ProgressBar style={{marginTop: -7, marginBottom: -7}} />
```

**Comment by Pika1998** [comment]
Thank you 😁
