### ISSUE TITLE
Unable to resolve module `react-native/Libraries/Utilities/codegenNativeComponent` 

### ISSUE THREAD

**Issue by venkataluri** [react-native-progress-view/progress-bar-android#51]
when i tried to run android application after installing this package i am getting the following error

**error: bundling failed: Error: Unable to resolve module `react-native/Libraries/Utilities/codegenNativeComponent` from `node_modules/@react-native-community/progress-bar-android/js/RNCProgressBarAndroidNativeComponent.js`: Module `react-native/Libraries/Utilities/codegenNativeComponent` does not exist in the Haste module map**

in react-native 0.60.5, codegenNativeComponent file is not present due.
Does progress-bar-android": "1.0.3" is supported for "react-native": "0.60.5"?

"@react-native-community/progress-bar-android": "1.0.3"
"react": "16.9.0"
"react-native": "0.60.5"

## Environment info

System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 371.68 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
npmPackages:
     react: 16.9.0 => 16.9.0 
    react-native: 0.60.5 => 0.60.5 

```

Library version: 1.0.3

**Comment by praveenp-od** [comment]
Any Solution?

**Comment by Naturalclar** [comment]
@venkataluri codegenNativeComponent is indeed not supported in RN0.60.5.
I'll try make a fix for this today

**Comment by venkataluri** [comment]
@Naturalclar any update on this issue?

**Comment by Shashank2406** [comment]
+1

**Comment by Nehal-29** [comment]
any update on this?

**Comment by adityasingh328** [comment]
any update on this?

**Comment by MathiasLund** [comment]
+1

**Comment by ThomLaGreca** [comment]
+1 Using ReactNative v59.9... Any ideas?

**Comment by krishanjangir** [comment]
+1 Using ReactNative v0.60.4... Any ideas?

**Comment by HaswinVidanage** [comment]
+1 Facing this on RN v0.60

**Comment by coderunnr** [comment]
+1 facing on RN 0.60.6. Do update if anyone finds a solution.

**Comment by rishiankush** [comment]
I fixed this issue by adding the file codegenNativeComponent.js to `node_modules/react-native/Libraries/Utilities`. Here is the code to add the file: https://github.com/facebook/react-native/blob/master/Libraries/Utilities/codegenNativeComponent.js

Not a good solution, just a trick and working like a charm.

**Comment by Naturalclar** [comment]
Sorry for the delay, I've published v1.0.4 which should fix the Issue.
